sources:
  - command: "mdfind kMDItemContentType == com.apple.application-* -attr kMDItemDisplayName | grep ^/Applications | sed s/...kMDItemDisplayName.=./:/"
    itemFormat: "(?P<data>.+):(?P<label>.+)"
    whenSelected: "open {data}"
    pinned: false
  # - command: "cash {input}"
  #   itemFormat: "{data}"
  #   whenSelected: |
  #     echo "{data}" | pbcopy
  #   pinned: true
  - command: trans --brief {input}
    itemFormat: "{data}"
    whenSelected: |
      echo "{data}" | pbcopy
    pinned: true
  - command: echo {input} | sed s/,/./g | bc
    itemFormat: "{data}"
    whenSelected: echo "{data}" | pbcopy
    pinned: true
